export const data =

    {
        "timeline": [{
            id: 1,
            type: 'course',
            row: 6,
            icon: 'bx bxs-check-shield',
            title: 'Programa Hackers do Bem - Básico',
            institution: 'Hackers do Bem | RNP | GovBR',
            period: '2024',
            startYear: 2024,
            duration: 1,
            description: 'Conhecimentos em computação em nuvem, fundamentos de desenvolvimento, ameaças e vulnerabilidades cibernéticas, criptografia e governança, risco e compliance (GRC)',
            url: 'https://ava.hackersdobem.org.br/badges/badge.php?hash=79b3c45db4ec904650b34c364c25195112d4aea9',
            validation: null
        },
            {
                id: 2,
                type: 'course',
                row: 3,
                icon: 'bx bxs-palette',
                title: 'Programa de cursos integrados Google UX Design',
                institution: 'Google',
                period: '2023 - 2024',
                startYear: 2023,
                duration: 2,
                description: 'Fundamentos de UX/UI, cobrindo pesquisa, prototipação, design no Figma, criação de interfaces e preparação para o mercado',
                url: 'https://www.coursera.org/account/accomplishments/specialization/4A9M46K2UT48',
                validation: null
            },
            {
                id: 3,
                type: 'course',
                row: 7,
                icon: 'bx bxl-postgresql',
                title: 'SQL para Análise de Dados: Do básico ao avançado',
                institution: 'Udemy',
                period: '2023',
                startYear: 2023,
                duration: 1,
                description: 'Curso dos fundamentos de SQL para análise de dados, incluindo consultas, joins, agregações, subqueries e tratamento de dados.',
                url: 'https://www.udemy.com/certificate/UC-fdfea483-be20-4b09-b3b6-4273c1a56ba9/',
                validation: null
            },
            {
                id: 4,
                type: 'course',
                row: 4,
                icon: 'bx bx-support',
                title: 'Programa de cursos integrados Suporte em TI do Google',
                institution: 'Google',
                period: '2023',
                startYear: 2023,
                duration: 1,
                description: 'Fundamentos de suporte técnico e infraestrutura de TI, abordando redes, sistemas operacionais, administração e segurança da informação.',
                url: 'https://www.coursera.org/account/accomplishments/specialization/J4QZX4DWSBPB',
                validation: null
            },
            {
                id: 5,
                type: 'work',
                row: 11,
                icon: 'bx bxs-bug',
                title: 'Automação de Testes em Java Back-end',
                institution: 'Compass UOL',
                period: '2023',
                startYear: 2023,
                duration: 1,
                description: 'Estágio: Participação na trilha de Automação de Testes Back-end em Java pelo Scholarship Program – Compass UOL (237h)',
                url: null,
                validation: null
            },
            {
                id: 6,
                type: 'course',
                row: 6,
                icon: 'bx bx-code-curly',
                title: 'Testando API Rest com REST-assured',
                institution: 'Udemy',
                period: '2023',
                startYear: 2023,
                duration: 1,
                description: 'Curso de testes de APIs REST em Java com REST Assured, abordando requisições, validações, autenticação, JSON/XML, arquivos e testes em API real',
                url: 'https://www.udemy.com/certificate/UC-156fcd7b-f643-4385-b833-781d5a46ef3d/',
                validation: null
            },
            {
                id: 7,
                type: 'course',
                row: 8,
                icon: 'bx bxs-book',
                title: 'Inglês Módulo 1 E-Tec Idiomas sem Fronteiras',
                institution: 'IFSUL',
                period: '2023',
                startYear: 2023,
                duration: 1,
                description: 'Curso de inglês 180 horas',
                url: 'https://moodle.ifsul.edu.br/novohamburgo/mod/simplecertificate/verify.php',
                validation: '64b87895-22bc-4a7e-b962-e78d0a00c840'
            },
            {
                id: 8,
                type: 'course',
                row: 5,
                icon: 'bx bxl-google-cloud',
                title: 'Google Cloud Computing',
                institution: 'Google Cloud',
                period: '2023',
                startYear: 2023,
                duration: 1,
                description: 'Certificações em fundamentos de Google Cloud, abrangendo cloud computing, infraestrutura, redes, segurança, balanceamento de carga e ambiente de desenvolvimento',
                url: 'https://www.cloudskillsboost.google/public_profiles/2523e458-4b1e-41b7-abf3-0e50a57c690f',
                validation: null
            },
            {
                id: 9,
                type: 'course',
                row: 8,
                icon: 'bx bxl-java',
                title: 'Dev The Devs',
                institution: 'PUCRS',
                period: '2021 - 2022',
                startYear: 2021,
                duration: 2,
                description: 'Fundamentos de computação e programação, com Java, HTML/CSS, Web e Spring Web Services',
                url: 'https://webappcl.pucrs.br/inscricoes/verificacao',
                validation: '202291-195-1'
            },
            {
                id: 10,
                type: 'certification',
                row: 9,
                icon: 'bx bx-math',
                title: 'Menção de honra OBMEP 2017',
                institution: 'OBMEP',
                period: '2017',
                startYear: 2017,
                duration: 1,
                description: 'Menção honrosa na Olimpíada Brasileira de Matemática',
                url: null,
                validation: null
            },
            {
                id: 11,
                type: 'certification',
                row: 9,
                icon: 'bx bx-math',
                title: 'Menção de honra OBMEP 2022',
                institution: 'OBMEP',
                period: '2022',
                startYear: 2022,
                duration: 1,
                description: 'Menção honrosa na Olimpíada Brasileira de Matemática',
                url: null,
                validation: null
            },
            {
                id: 11,
                type: 'academic',
                row: 10,
                icon: 'bx bxs-book',
                title: 'Bacharelado, Ciência da Computação',
                institution: 'Atitus Educação',
                period: '2023',
                startYear: 2023,
                duration: 4,
                description: 'Formação sólida em Ciência da Computação, abrangendo pensamento computacional, algoritmos, programação e engenharia de software. Desenvolvimento de aplicações front-end, foco em UX, organização e abstração de código. Conhecimentos em engenharia de dados, bancos de dados e otimização, além de paradigmas de linguagens de programação. Atuação em machine learning, inteligência artificial e big data. Fundamentos e prática em cloud computing, arquitetura de soluções, cibersegurança e computação distribuída. Base consistente em sistemas operacionais, arquitetura de hardware, além de computação gráfica, linguagens formais, compiladores, tecnologias emergentes, gestão de projetos, inovação e empreendedorismo',
                url: null,
                validation: null
            },
            {
                id: 12,
                type: 'work',
                row: 11,
                icon: 'bx bxs-bug',
                title: 'Automatizador de Testes',
                institution: 'Spread Tecnologia',
                period: '2024 - Atual',
                startYear: 2024,
                duration: 2,
                description: 'Atuação em automação de testes em Java para Big Data, com validação de ETL/ELT no Databricks, testes funcionais e de performance, uso de boas práticas (DDT, BDD, Shift-Left) e integração com Azure, Spark e bancos de dados',
                url: null,
                validation: null
            },
            {
                id: 13,
                type: 'course',
                row: 8,
                icon: 'bx bxs-data',
                title: 'Get Started with SQL Analytics and BI on Databricks - Portuguese BR',
                institution: 'Databricks',
                period: '2025',
                startYear: 2025,
                duration: 1,
                description: 'Curso introdutório e prático sobre análise de dados no Databricks, focado em Data Intelligence, SQL, Delta Lake e dashboards com IA para tomada de decisões mais rápidas',
                url: null,
                validation: null
            },
            {
                id: 14,
                type: 'work',
                row: 11,
                icon: 'bx bxs-briefcase',
                title: 'Auxiliar de Escritório',
                institution: 'Mirasul',
                period: '2022 - 2023',
                startYear: 2022,
                duration: 1,
                description: 'Jovem Aprendiz - SENAI - Operador de processo logísticos e industriais, atividades administrativas e suporte de TI',
                url: null,
                validation: null
            },
            {
                id: 15,
                type: 'course',
                row: 7,
                icon: 'bx bxs-microchip',
                title: 'Curso de eletrônica, manutenção e configuração de computadores',
                institution: 'Método MW 4.0',
                period: '2025',
                startYear: 2025,
                duration: 1,
                description: 'Limpeza, manutenção, montagem, configuração de hardware e software, redes de computadores e segurança da informação',
                url: 'https://hotmart.com/pt-br/club/metodo-mw-40/product/2206949/certificate/57514c09-fc38-4e9d-bb81-7bc6d33ea515--635568224/validate',
                validation: null
            },
            {
                id: 16,
                type: 'course',
                row: 2,
                icon: 'bx bxl-java',
                title: 'Boas práticas de programação: melhore o código de uma API Java',
                institution: 'Alura',
                period: '2024',
                startYear: 2024,
                duration: 1,
                description: 'Boas práticas de arquitetura e persistência, incluindo separação de responsabilidades, uso de DTO, validações flexíveis e otimizações de desempenho',
                url: 'https://cursos.alura.com.br/certificate/higor-milani/boas-praticas-programacao-melhore-codigo-api-java',
                validation: null
            },
            {
                id: 17,
                type: 'course',
                row: 4,
                icon: 'bx bxl-java',
                title: 'Java e refatoração: melhorando códigos com boas práticas',
                institution: 'Alura',
                period: '2024',
                startYear: 2024,
                duration: 1,
                description: 'Práticas de engenharia de software, com foco em refatoração, princípios SOLID, modelagem de domínios, testes automatizados e padrões de projeto',
                url: 'https://cursos.alura.com.br/certificate/higor-milani/java-refatoracao-melhorando-codigos-boas-praticas',
                validation: null
            },
            {
                id: 18,
                type: 'certification',
                row: 8,
                icon: 'bx bx-shield-quarter',
                title: 'Qualificação em Arquitetura de Soluções em Cloud',
                institution: 'Atitus Educação',
                period: '2024',
                startYear: 2024,
                duration: 1,
                description: 'Estudos em comportamento e fatores humanos no desenvolvimento de software, fundamentos de cibersegurança e computação em nuvem (SaaS, PaaS, IaaS), com foco em arquitetura, gestão e segurança de sistemas escaláveis, pentesting, kali Linux e redes',
                url: 'https://atitusvalidador.web.app/',
                validation: 'cc47d4a3db41'
            },
            {
                id: 19,
                type: 'course',
                row: 5,
                icon: 'bx bx-shield-quarter',
                title: 'Programa Hackers do Bem - Fundamental',
                institution: 'Hackers do Bem | RNP | GovBR',
                period: '2024',
                startYear: 2024,
                duration: 1,
                description: 'Fundamentos de segurança da informação, cobrindo ameaças e malwares, controles de acesso, IAM, criptografia, redes e hosts seguros, proteção web, backups, PKI/Blockchain e resposta a incidentes',
                url: 'https://ava.hackersdobem.org.br/badges/badge.php?hash=5eaaeb9219184eee57ab0601dee87abdb7cd27cc',
                validation: null
            },
            {
                id: 20,
                type: 'course',
                row: 7,
                icon: 'bx bx-shield-quarter',
                title: 'Programa Hackers do Bem - Nivelamento',
                institution: 'Hackers do Bem | RNP | GovBR',
                period: '2024',
                startYear: 2024,
                duration: 1,
                description: 'Fundamentos de cibersegurança, redes de computadores (TCP/IP, IPv6), hardware, Windows e Linux, além de lógica de programação e desenvolvimento de scripts',
                url: 'https://ava.hackersdobem.org.br/badges/badge.php?hash=3feb070ed8e6f9cef27543405d9faf48adaacecc',
                validation: null
            },
            {
                id: 21,
                type: 'course',
                row: 1,
                icon: 'bx bxl-aws',
                title: 'AWS Academy Graduate - Introduction to Cloud Semester 1 - Training Badge',
                institution: 'AWS Academy',
                period: '2024',
                startYear: 2024,
                duration: 1,
                description: 'Curso introdutório de AWS Cloud, abordando fundamentos de cloud computing, arquitetura, segurança, custos, suporte e uso do AWS Management Console em cenários práticos',
                url: 'https://www.credly.com/badges/133ede12-4023-423b-9dab-e206664835d1/print',
                validation: null
            },
            {
                id: 22,
                type: 'certification',
                row: 9,
                icon: 'bx bxl-aws',
                title: 'Oratória nas Escolas',
                institution: 'JCI (Junior Chamber International)',
                period: '2021',
                startYear: 2021,
                duration: 1,
                description: 'Programa de Ortória nas Escolas, focado em habilidades de comunicação e apresentação em público',
                url: null,
                validation: null
            },
            {
                id: 23,
                type: 'certification',
                row: 9,
                icon: 'bx bx-code-block',
                title: 'Qualificação em Desenvolvimento de Soluções Full Stack',
                institution: 'Atitus Educação',
                period: '2023',
                startYear: 2023,
                duration: 1,
                description: 'Estudos em organização e abstração de código, desenvolvimento de APIs com Spring Boot, design centrado no usuário (UX) e desenvolvimento de interfaces web com React, focando usabilidade e responsividade',
                url: 'https://atitusvalidador.web.app/',
                validation: 'cc1353dc2730'
            },
            {
                id: 24,
                type: 'certification',
                row: 9,
                icon: 'bx bxs-devices',
                title: 'Qualificação em Engenharia de Software',
                institution: 'Atitus Educação',
                period: '2024',
                startYear: 2024,
                duration: 1,
                description: 'Desenvolvimento de comunicação técnica, design e engenharia de processos, otimização de bancos de dados e estudo de paradigmas de programação, React Native e desenvolvimento mobile, Arquitetura, documentação e metodologias ágeis',
                url: 'https://atitusvalidador.web.app/',
                validation: 'cc9fbf2b7bfe'
            },
            {
                id: 25,
                type: 'certification',
                row: 9,
                icon: 'bx bx-bot',
                title: 'Qualificação em Inteligência Artificial, Machine Learning e Big Data',
                institution: 'Atitus Educação',
                period: '2025',
                startYear: 2025,
                duration: 1,
                description: 'Conhecimentos em inteligência artificial e machine learning (redes neurais, CNNs, regressão, análise de dados com Python), gestão de projetos baseada no PMBOK e métodos ágeis, e Big Data com Hadoop, Spark, Databricks e NoSQL',
                url: 'https://atitusvalidador.web.app/',
                validation: 'cc7f06a17681'
            }
        ],


        "servicos": [
            {
                id: 1,
                icon: "bx bx-code-block",
                title: "Front-end Development",
                description: "Eu trabalho com HTML, CSS, JavaScript, além de um pouco de Back-end para poder dar mais capacidade aos meus projetos. Aprofundei meus conhecimentos com os cursos da Rocketseat, W3schools, SENAI e na faculdade.",
                popup_title: "FRONT-END",
                popup_cite: "O que o usuário vê o coração",
                popup_cite_span: "sente",
                popup_cite_author: " ",
                popup_url_big_img: "./img/Servicos/front-end/front-end.png",
                popup_url_small_img: "./img/Servicos/front-end/aside.png",
                popup_about_title: "Front-end",
                popup_about_description_p1: "Como eu gosto de programar, e também de design, trabalhar como front-end é bem satisfatório para mim. Eu gosto de criar e pensar em como as pessoas vão interagir com minhas criações. A interface de um programa ou site pode ser a diferença para o agrado do usuário.",
                popup_about_description_p2: "Eu trabalho com HTML, CSS, JavaScript, além de um pouco de Back-end para poder dar mais redundância aos meus projetos. Aprofundei meus conhecimentos com os cursos da Rocketseat, W3schools, SENAI e na faculdade. Garantir a qualidade e a segurança é essencial para um site ou programa.",
                popup_about_description_p3: "O potencial que uma página web pode proporcionar é incrível, lojas, blogs, site de notícias, buscadores, softwares. Tudo depende da criatividade de seu desenvolvedor. E eu posso ser esse desenvolvedor.",
                popup_btn: "Trabalhos",
                popup_btn_url: "https://higor-h.github.io/PrevisaoDoTempo/",
                popup_btn_download: null
            },
            {
                id: 2,
                icon: "bx bxs-paint",
                title: "Design Gráfico",
                description: "Eu trabalho com design para as mais diversas áreas e funções, procuro sempre fazer trabalhos únicos, neles eu gosto de me extrair o objetivo do projeto e fazer algo realmente marcante com ele. ",
                popup_title: "MEUS DESIGNS",
                popup_cite: "Design não é apenas o que parece é o que se sente. Design é como ",
                popup_cite_span: "funciona",
                popup_cite_author: "-Steve Jobs",
                popup_url_big_img: "./img/Servicos/design/design.png",
                popup_url_small_img: "./img/Servicos/design/aside.png",
                popup_about_title: "Design",
                popup_about_description_p1: "Eu me aventuro em designs, além de ser uma área que eu tenho interesse, ela é fascinante pois integra conceitos de cores, formas, composições e principalmente a psique humana, o design está presente em todas coisas de nosso dia a dia, cada formato, cada forma está lá por algum motivo, alguém pensou, estudou e planejou para que sua obra passa se o que lhe era desejado. Móveis, pinturas, aparelhos eletrônicos, sites, programas, maquiagem, fotografia, estruturas… tudo é design, tudo é arte.",
                popup_about_description_p2: "Um bom design desperta emoções e experiências e é isso que eu tento trazer em cada projeto e em cada trabalho meu, eu utilizo diversas ferramentas para criar os meus designs, a internet trouxe um mar de ferramentas, inspirações, feedbacks e conhecimentos, eu sempre tento usar isso ao meu favor.",
                popup_about_description_p3: "Trabalho em sites, panfletos, cartas, apresentações, marca páginas, capas de livros, Logos… Como faço trabalhos personalizados cada design é diferente do outro, procuro entender o objetivo do trabalho e fazer dele único. veja meus trabalhos em meu portfólio no botão abaixo:",
                popup_btn: "Trabalhos",
                popup_btn_url: "./img/Meus_Designs.pdf",
                popup_btn_download: "Design Higor Milani"
            },
            {
                id: 3,
                icon: "bx bx-code-alt",
                title: "Programação",
                description: "Eu programo principalmente em Python e em Java, essas duas linguagens são as mais utilizadas hoje em dia. elas têm uma grande comunidade e muito repertório e conteúdo para estudar e programar. ",
                popup_title: "PROGRAMAÇÃO",
                popup_cite: "Todas as pessoas deveriam aprender a programar, pois isso ensina a ",
                popup_cite_span: "pensar",
                popup_cite_author: "-Steve Jobs",
                popup_url_big_img: "./img/Servicos/progamacao/progamacao.png",
                popup_url_small_img: "./img/Servicos/progamacao/aside.png",
                popup_about_title: "Programação",
                popup_about_description_p1: "Programar, ou entender como ela funciona é essencial para compreender o mundo em que vivemos, toda a tecnologia moderna trabalha graças a sua programação, desde as linguagens de mais baixo nível até as de mais alto nível, hoje em dia é possível criar a sua própria linguagem de programação. ",
                popup_about_description_p2: "Eu programo principalmente em Python e em Java, essas duas linguagens são umas das mais utilizadas hoje em dia. elas têm uma grande comunidade e muito repertório e conteúdo para estudar e programar, porém eu também pretendo aprender mais linguagens para aumentar minhas capacidades.",
                popup_about_description_p3: "Programar é um facilitador que proporciona inúmeras automatizações, projetos, tanto com softwares como com hardwares. Trabalhar com programação é muito útil pois elas são flexíveis e permitem correções e otimizações em seu projeto, para ele ficar sempre atual e funcional, um hardware pode ficar antigo e impossível de atualizar, mas um software não. Veja meus trabalhos em meu portfólio no botão abaixo:",
                popup_btn: "Trabalhos",
                popup_btn_url: "https://github.com/Higor-H/Progaming",
                popup_btn_download: null
            },
            {
                id: 4,
                icon: "bx bxl-dev-to",
                title: "Back-end Developer",
                description: "Eu trabalho com back-end usando Java, e tenho experiências em Google Cloud Platform (GCP), ganhei experiência em testes e automação na minha bolsa de estudos na Compass UOL. ",
                popup_title: "BACK-END",
                popup_cite: "A arte de programar consiste na arte de organizar e dominar a ",
                popup_cite_span: "complexidade",
                popup_cite_author: "-Dijkstra",
                popup_url_big_img: "./img/Servicos/back-end/back-end.png",
                popup_url_small_img: "./img/Servicos/back-end/aside.png",
                popup_about_title: "Back-end",
                popup_about_description_p1: "O back-end de um programa ou site é uma das partes mais fundamentais de um sistema, afinal é graças a ele que tudo ganha ''vida'' gerenciar, processar, guardar, receber, e enviar dados, o back-end é indispensável para qualquer aplicação, um bom back-end é essencial para a segurança, privacidade, velocidade e usabilidade que qualquer sistema. ",
                popup_about_description_p2: "Com minha experiência em programação em Java, além dos cursos do Google Cloud Platform (GCP), Uma grande experiência em Back-end é minha bolsa de estudos na Compass UOL, nela eu tive estudos na área de Scrum e QA, onde todos os conteúdos foram documentados através do Git no GitLab durante as Sprints, os estudos abordaram os fundamento de software, como planejar e documentar testes tendo sempre em vista como eles são importantes para gerar valor para a aplicação, saber reportar os bugs e melhorias nas issues, também realizamos automação de testes usando RestAssured.",
                popup_about_description_p3: "Garantir um código ótimo, rápido, simples e que possa ser atualizado e entendido por mais programadores da equipe fazem  um diferencial em grandes projetos, a otimização é importante para a agilidade de um servidor ou programa,  afinal tudo está conectado e avançado nos dias de hoje, em função disso devemos acompanhar tal progresso. Veja meus trabalhos em meu portfólio no botão abaixo:  ",
                popup_btn: "Trabalhos",
                popup_btn_url: "https://gitlab.com/higor_sprints",
                popup_btn_download: null
            }

        ]
    }